# Generated by Django 4.2.7 on 2025-09-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('active', '进行中'), ('completed', '已完成'), ('suspended', '暂停'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目所有者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工地名称')),
                ('description', models.TextField(blank=True, verbose_name='工地描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='工地地址')),
                ('site_manager', models.CharField(blank=True, max_length=100, verbose_name='工地负责人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('active', '施工中'), ('completed', '已完成'), ('suspended', '暂停')], default='preparing', max_length=20, verbose_name='工地状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksites', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工地',
                'verbose_name_plural': '工地',
                'ordering': ['-created_at'],
            },
        ),
    ]
