# Generated by Django 4.2.7 on 2025-09-06 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 9, 6), verbose_name='结束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksite',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 9, 6), verbose_name='开始日期'),
            preserve_default=False,
        ),
    ]
