# Generated by Django 4.2.7 on 2025-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '开放'), ('in_progress', '进行中'), ('pending', '待处理'), ('completed', '已完成')], default='open', max_length=20, verbose_name='任务状态'),
        ),
    ]
