# Generated by Django 4.2.7 on 2025-09-06 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='此任务依赖的其他任务（必须等待这些任务完成后才能开始）', related_name='dependent_tasks', to='tasks.task', verbose_name='依赖任务'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 9, 6), verbose_name='结束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 9, 6), verbose_name='开始日期'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('finish_to_start', '完成-开始'), ('start_to_start', '开始-开始'), ('finish_to_finish', '完成-完成'), ('start_to_finish', '开始-完成')], default='finish_to_start', max_length=20, verbose_name='依赖类型')),
                ('lag_days', models.IntegerField(default=0, help_text='依赖关系的延迟天数（可以为负数表示提前）', verbose_name='滞后天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='tasks.task', verbose_name='前置任务')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='tasks.task', verbose_name='后续任务')),
            ],
            options={
                'verbose_name': '任务依赖',
                'verbose_name_plural': '任务依赖',
                'ordering': ['created_at'],
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
