# Generated by Django 4.2.7 on 2025-09-04 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drawings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='图纸名称')),
                ('file', models.FileField(upload_to=drawings.models.drawing_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'bmp', 'tiff'])], verbose_name='图纸文件')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='页数')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='文件类型')),
                ('pdf_version', models.CharField(blank=True, max_length=10, verbose_name='PDF版本')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=drawings.models.thumbnail_upload_path, verbose_name='缩略图')),
                ('is_valid', models.BooleanField(default=True, verbose_name='文件完整性')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.worksite', verbose_name='所属工地')),
            ],
            options={
                'verbose_name': 'PDF图纸',
                'verbose_name_plural': 'PDF图纸',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
