# Generated by Django 4.2.7 on 2025-08-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('new_construction', '新建施工'), ('repair', '整改修复'), ('inspection', '检查验收'), ('maintenance', '维护保养')], default='new_construction', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='负责人')),
                ('deadline', models.DateField(verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('drawings', models.ManyToManyField(blank=True, related_name='tasks', to='drawings.drawing', verbose_name='关联图纸')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('point', '点标记'), ('rectangle', '矩形标记'), ('text', '文字标注'), ('line', '线条标注')], max_length=20, verbose_name='标注类型')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='页码')),
                ('x_coordinate', models.FloatField(verbose_name='X坐标')),
                ('y_coordinate', models.FloatField(verbose_name='Y坐标')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='高度')),
                ('end_x', models.FloatField(blank=True, null=True, verbose_name='终点X坐标')),
                ('end_y', models.FloatField(blank=True, null=True, verbose_name='终点Y坐标')),
                ('color', models.CharField(choices=[('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('yellow', '黄色'), ('orange', '橙色'), ('purple', '紫色'), ('black', '黑色')], default='red', max_length=20, verbose_name='标注颜色')),
                ('content', models.TextField(max_length=200, verbose_name='标注内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='drawings.drawing', verbose_name='关联图纸')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tasks.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务标注',
                'verbose_name_plural': '任务标注',
                'ordering': ['created_at'],
            },
        ),
    ]
